### ISSUE TITLE
Timeout on Client::submitJob

### ISSUE THREAD

**Issue by samlikins** [kicken/gearman-php#1]
In the case where the Job Server is running, but no worker is registered to handle a foreground job, the process hangs (waiting on a Job handel).  The client needs a timeout that can be set to provide a way to deal with a non-response.

Example of method from PECL Gearman Client class: http://php.net/manual/en/gearmanclient.settimeout.php

**Comment by samlikins** [comment]
Upon further investigation, I found that the issue exists in ```Connection::read()```

```php
    private function read($length){
        if (!$this->stream || feof($this->stream)){
            throw new NotConnectedException;
        }

        do {
            $data = fread($this->stream, $length);
            if ($data === '' && feof($this->stream)){
                throw new LostConnectionException;
            }
        } while ($data === '');

        return $data;
    }
```

When the job being requested isn't registered, the process is caught in the ```fread()``` loop.  Even with adding ```stream_set_timeout($this->stream, 5)``` prior to the loop, execution will continue looping; the ```fread()``` just times out sooner.

```
PHP Stack trace:
PHP   1: {main}() example.php:0
PHP   2: Kicken\Gearman\Client->wait($for = *uninitialized*) example.php:25
PHP   3: Kicken\Gearman\Client->packetIteration() src/Client.php:160
PHP   4: Kicken\Gearman\Protocol\Connection->readPacket() src/Client.php:165
PHP   5: Kicken\Gearman\Protocol\Connection->read($length = 12) src/Protocol/Connection.php:94
```

Their has to be a simple solution to this, that will allow a timeout to be set after creation of the Client.  Hope this helps to narrow down the search for a cure.

**Comment by kicken** [comment]
I've put some preliminary changes up on a new branch (issue-1) if you would like to give them a try.  I still need to do some further testing before merging to master.

**Comment by samlikins** [comment]
I switch branches in my project to ```issue-1```, added a call to ```Client::setTimeout()```, and added in ```try```/```catch``` blocks to finish it all off.  I ran the code (again without the worker registered with the server) and watched as it gracefully failed.  I'd have to say that the changes worked for my use.

I did have a question in regards to the worker having a timeout; in what situation would that timeout be effective?

Thanks for the rather quick response in finding a solution, let me know if I can assist in getting these changes to release.

**Comment by kicken** [comment]
I added the worker timeout mostly for symmetry and because the PECL GearmanWorker class has one as well.  Setting a timeout does help with detecting if the network link fails while waiting for work.

**Comment by kicken** [comment]
Merged the changes to master.  Thanks for the help.

**Comment by samlikins** [comment]
**Request**:  Would you add a release version for the master branch?  You could mark the previous commit on ```master``` as ```v1.0.0``` and this last commit as ```v1.1.0```.  This will make adding this library via Composer more comfortable for other projects.

Then you could add the following to the readme:

----

## Installation

Add following line to your composer.json require:
```json
    "kicken/gearman-php": "^1"
```

Alternately you can use following command:
```bash
composer.phar require kicken/gearman-php:^1
```

----

Thanks again for your efforts in correcting this issue.
