### ISSUE TITLE
Submitting large numbers of jobs at once results in exponential slowdown

### ISSUE THREAD

**Issue by Firehed** [kicken/gearman-php#7]
The job tracking in `Client` (`$this->jobList`) will grow indefinitely, and subsequent iteration that happens when submitting jobs slows to a crawl. For some concrete numbers, the first ~3000 jobs fire off in a second or two, but it takes almost a full minute to submit 10000 at a time. For "fire and forget" jobs (e.g. background jobs where you don't care about checking the status), this gets to be fairly unpleasant.

**Comment by kicken** [comment]
I've pushed v1.4.0 which should speed this up.  In my tests the time required to submit 10,000 background jobs dropped from about 20 seconds to 3 seconds.
